pipeline {
  agent any

  environment {
    AWS_DEFAULT_REGION = 'us-east-1'
    S3_BUCKET = 'poc-enterprise-hr-frontend-842806122556'
    CF_DIST_ID = 'E1PR9TUS2OTIXH'
  }

  stages {
    stage('Install') {
      steps {
        dir('poc-frontend-ui') {
          sh 'npm ci'
        }
      }
    }

    stage('Build') {
      steps {
        dir('poc-frontend-ui') {
          sh 'npm run build'
        }
      }
    }

    stage('Deploy') {
      steps {
        withCredentials([usernamePassword(credentialsId: 'aws-creds',
                         usernameVariable: 'AWS_ACCESS_KEY_ID',
                         passwordVariable: 'AWS_SECRET_ACCESS_KEY')]) {
          dir('poc-frontend-ui') {
            sh '''
              aws s3 sync dist/ s3://${S3_BUCKET} --delete
              aws cloudfront create-invalidation \
                --distribution-id ${CF_DIST_ID} \
                --paths "/*"
              echo "Frontend deployed to S3 and CloudFront cache invalidated"
            '''
          }
        }
      }
    }
  }

  post {
    success {
      echo 'Frontend deployed successfully'
    }
    failure {
      echo 'Frontend deployment failed'
    }
  }
}
